import { appSectionIds } from "@/shared/config/app";

export const productsHeroContent = {
  id: appSectionIds.products,
  badge: "DANH MỤC SẢN PHẨM",
  titleParts: ["CÁC DÒNG ", "VÁN PHỦ PHIM"],
  description: [
    "Đa dạng độ dày và chủng loại phim để đáp ứng mọi yêu cầu kỹ thuật từ công trình dân",
    "dụng đến công nghiệp nặng.",
  ],
  filterButtons: ["TẤT CẢ", "TIÊU CHUẨN", "CAO CẤP"],
  products: [
    {
      image: "/assets/products/catalog/catalog-12mm.jpg",
      badge: { label: "TIÊU CHUẨN", color: "rgba(41,115,178,1)" },
      inStock: true,
      hotSale: false,
      hotTag: false,
      tags: ["WBP Phenolic", "Phim Đen", "8–12 lần"],
      name: "Ván Phủ Phim 12mm",
      subName: "Gỗ Bạch Dương · Dynea Đen",
      description: [
        "Phù hợp với các công trình dân dụng nhỏ và vừa.",
        "Lõi bạch dương nhẹ, dễ thi công, phủ phim Dynea",
        "đen chống thấm WBP.",
      ],
      specs: [
        { value: "12mm", label: "Độ dày" },
        { value: "1220×2440", label: "Kích thước" },
        { value: "8–12×", label: "Tái sử dụng" },
      ],
      isPremium: false,
    },
    {
      image: "/assets/products/catalog/catalog-15mm.jpg",
      badge: { label: "PHỔ BIẾN", color: "rgba(72,166,167,1)" },
      inStock: true,
      hotSale: false,
      hotTag: false,
      tags: ["WBP Phenolic", "Phim Nâu", "10–12 lần"],
      name: "Ván Phủ Phim 15mm",
      subName: "Gỗ Keo · Dynea Nâu",
      description: [
        "Dòng sản phẩm phổ biến nhất — độ bền cao, chịu",
        "tải trọng tốt cho cột, dầm bê tông. Gỗ keo nhiệt",
        "đới với phim nâu Dynea cao cấp.",
      ],
      specs: [
        { value: "15mm", label: "Độ dày" },
        { value: "1220×2440", label: "Kích thước" },
        { value: "10–12×", label: "Tái sử dụng" },
      ],
      isPremium: false,
    },
    {
      image: "/assets/products/catalog/catalog-18mm.jpg",
      badge: { label: "CAO CẤP", color: "rgba(41,115,178,1)" },
      hotSale: true,
      inStock: false,
      hotTag: false,
      tags: ["WBP Phenolic", "Phim Đen 120g", "12–15 lần"],
      name: "Ván Phủ Phim 18mm",
      subName: "Gỗ Bạch Dương · Dynea Đen 120g",
      description: [
        "Dòng cao cấp nhất — lõi bạch dương toàn phần,",
        "phủ phim Dynea đen 120g/m², 11 lớp ép nhiệt.",
        "Dành cho công trình cao tầng, chịu tải nặng.",
      ],
      specs: [
        { value: "18mm", label: "Độ dày" },
        { value: "1220×2440", label: "Kích thước" },
        { value: "12–15×", label: "Tái sử dụng" },
      ],
      isPremium: true,
    },
    {
      image: "/assets/products/catalog/catalog-21mm.jpg",
      badge: { label: "SIÊU DÀY", color: "rgba(51,51,51,1)" },
      inStock: true,
      hotSale: false,
      hotTag: false,
      tags: ["WBP Phenolic", "Phim Đen", "12–15 lần"],
      name: "Ván Phủ Phim 21mm",
      subName: "Gỗ Bạch Dương · Dynea Đen",
      description: [
        "Độ dày tối đa, phù hợp cho các ván đà, cốp pha",
        "sàn và công trình chịu lực đặc biệt. 13 lớp gỗ bạch",
        "dương ép nhiệt tiêu chuẩn.",
      ],
      specs: [
        { value: "21mm", label: "Độ dày" },
        { value: "1220×2440", label: "Kích thước" },
        { value: "12–15×", label: "Tái sử dụng" },
      ],
      isPremium: false,
    },
    {
      image: "/assets/products/catalog/catalog-melamine.jpg",
      badge: { label: "MELAMINE", color: "rgba(72,166,167,1)" },
      inStock: true,
      hotSale: false,
      hotTag: false,
      tags: ["Melamine", "Trắng", "8–10 lần"],
      name: "Ván Melamine 15mm",
      subName: "Gỗ Tạp · Phim Melamine Trắng",
      description: [
        "Phủ phim Melamine sáng màu — bề mặt trắng",
        "sạch, phù hợp cho nội thất, vách ngăn và ốp trần",
        "nhà. Phát thải thấp E1.",
      ],
      specs: [
        { value: "15mm", label: "Độ dày" },
        { value: "1220×2440", label: "Kích thước" },
        { value: "8–10×", label: "Tái sử dụng" },
      ],
      isPremium: false,
    },
    {
      image: "/assets/products/catalog/catalog-birch18mm.jpg",
      badge: { label: "FULL BIRCH", color: "rgba(41,115,178,1)" },
      inStock: false,
      hotSale: false,
      hotTag: true,
      tags: ["WBP Phenolic", "Full Birch", "15 lần"],
      name: "Full Birch 18mm",
      subName: "100% Gỗ Bạch Dương · Dynea Đen",
      description: [
        "Tất cả lõi gỗ bạch dương cao cấp 100%, mật độ",
        "tối đa, khả năng chịu lực vượt trội. Xuất khẩu sang",
        "thị trường châu Âu và Nhật Bản.",
      ],
      specs: [
        { value: "18mm", label: "Độ dày" },
        { value: "1220×2440", label: "Kích thước" },
        { value: "15×", label: "Tái sử dụng" },
      ],
      isPremium: true,
    },
  ],
} as const;
