export const contactFaqContent = {
  id: "lien-he-form",
  heading: "GỬI YÊU CẦU",
  headingHighlight: "CỦA BẠN",
  badge: "LIÊN HỆ",
  subtitle: [
    "Điền vào biểu mẫu bên dưới hoặc liên hệ trực tiếp — chúng tôi phản hồi",
    "trong vòng 30 phút trong giờ làm việc.",
  ],
  form: {
    title: "BIỂU MẪU LIÊN HỆ",
    nameLabel: "Họ Và Tên",
    namePlaceholder: "Nguyễn Văn A",
    companyLabel: "Công Ty / Đơn Vị",
    companyPlaceholder: "Tên công ty (nếu có)",
    phoneLabel: "Số Điện Thoại",
    phonePlaceholder: "0983 570 760",
    emailLabel: "Email",
    emailPlaceholder: "email@example.com",
    subjectLabel: "Chủ Đề / Sản Phẩm Quan Tâm",
    subjectPlaceholder: "-- Chọn sản phẩm / chủ đề --",
    subjectOptions: [
      { value: "van-ep-phu-phim", label: "Ván ép phủ phim" },
      { value: "van-ep-noi-that", label: "Ván ép nội thất" },
      { value: "van-ep-cong-nghiep", label: "Ván ép công nghiệp" },
      { value: "gian-giao", label: "Giàn giáo xây dựng" },
      { value: "khac", label: "Khác" },
    ],
    quantityLabel: "Số Lượng Dự Kiến",
    quantityPlaceholder: "Ví dụ: 500 tấm, 20m³...",
    messageLabel: "Nội Dung Tin Nhắn",
    messagePlaceholder: "Mô tả chi tiết yêu cầu của bạn — công trình, địa điểm giao hàng, thời gian cần hàng...",
    submitLabel: "GỬI YÊU CẦU BÁO GIÁ",
    securityNote: "Thông tin của bạn được bảo mật hoàn toàn.",
  },
  address: {
    badge: "ĐỊA CHỈ NHÀ MÁY",
    title: "KCN Hồ Điền, Đan Phượng",
    line1: "Khu công nghiệp Hồ Điền, Liên Trung, Đan",
    line2: "Phượng, Hà Nội, Việt Nam",
    linkLabel: "Xem bản đồ",
    linkHref: "#",
  },
  phone: {
    badge: "HOTLINE TƯ VẤN",
    number: "0983 570 760",
    secondary: "096 646 7895",
    status: "Đang hoạt động — Thứ 2–7 / 7:30–17:30",
  },
  email: {
    badge: "EMAIL",
    address: "admin@vanphuphim.vn.com",
    note: "Phản hồi trong vòng 2–4 giờ làm việc",
    linkLabel: "Gửi email ngay",
    linkHref: "mailto:admin@vanphuphim.vn.com",
  },
  hours: {
    badge: "GIỜ LÀM VIỆC",
    weekdays: { label: "Thứ 2 – Thứ 6", value: "7:30 – 17:30" },
    saturday: { label: "Thứ 7", value: "7:30 – 12:00" },
    sunday: { label: "Chủ Nhật", value: "NGHỈ" },
  },
  social: {
    badge: "THEO DÕI CHÚNG TÔI",
    title: "Cập nhật dự án & sản phẩm mới nhất",
  },
} as const;
