export const newsGridContent = {
  header: {
    badge: "BÀI VIẾT MỚI NHẤT",
    showing: "Hiển thị 6 / 24 bài viết",
  },
  cards: [
    {
      image: "/assets/news/grid/card-1.jpg",
      alt: "construction site with workers unloading plywood sheets from trucks",
      day: "10",
      month: "Th.7",
      category: "TIN THỊ TRƯỜNG",
      categoryBg: "#48a6a7",
      title: ["GIÁ VÁN ÉP PHỦ PHIM", "Q3/2025 ỔN ĐỊNH NHỜ", "NGUỒN CUNG DỒI DÀO", "TỪ MIỀN BẮC"],
      description: [
        "Thị trường vật liệu xây dựng",
        "miền Bắc ghi nhận sự ổn định",
        "về giá trong quý III, với nguồn",
        "cung từ các nhà máy lớn như",
        "Tu Anh 68 đảm bảo đáp ứng",
        "nhu cầu ngày càng tăng cao.",
      ],
      views: "1,204",
    },
    {
      image: "/assets/news/grid/card-2.jpg",
      alt: "close-up of plywood cross-section layers showing glue lines",
      day: "05",
      month: "Th.7",
      category: "KỸ THUẬT",
      categoryBg: "#2973b2",
      title: ["HƯỚNG DẪN CHỌN ĐỘ", "DÀY VÁN ÉP PHỦ PHIM", "PHÙ HỢP CHO TỪNG", "LOẠI CÔNG TRÌNH"],
      description: [
        "Từ móng nhà dân dụng đến",
        "cầu đường và nhà cao tầng,",
        "mỗi loại công trình đòi hỏi độ",
        "dày ván coffa khác nhau. Kỹ",
        "sư Tu Anh 68 hướng dẫn chi",
        "tiết cách lựa chọn tối ưu.",
      ],
      views: "3,581",
    },
    {
      image: "/assets/news/grid/card-3.jpg",
      alt: "business exhibition hall with industrial plywood manufacturer booth",
      day: "28",
      month: "Th.6",
      category: "SỰ KIỆN",
      categoryBg: "#7a9c59",
      title: ["TU ANH 68 THAM GIA", "VIETNAM BUILD EXPO", "2025 — GIỚI THIỆU", "DÒNG VÁN MỚI"],
      description: [
        "Tại hội chợ vật liệu xây dựng",
        "lớn nhất năm, Tu Anh 68 ra",
        "mắt dòng ván ép phủ phim",
        "đen 240g/m² cao cấp và",
        "nhận được sự quan tâm đặc",
        "biệt từ các nhà thầu lớn.",
      ],
      views: "987",
    },
    {
      image: "/assets/news/grid/card-4.jpg",
      alt: "aerial view of Vietnam construction boom with multiple high-rise buildings",
      day: "20",
      month: "Th.6",
      category: "TIN THỊ TRƯỜNG",
      categoryBg: "#48a6a7",
      title: ["NHU CẦU VÁN COFFA", "TĂNG 35% THEO LÀN", "SÓNG ĐẦU TƯ HẠ TẦNG", "2025–2030"],
      description: [
        "Gói đầu tư công 800.000 tỷ",
        "đồng của Chính phủ cho giai",
        "đoạn 2025–2030 đang tạo ra",
        "nhu cầu khổng lồ cho vật liệu",
        "coffa, đặc biệt là ván ép phủ",
        "phim chất lượng cao.",
      ],
      views: "2,115",
    },
    {
      image: "/assets/news/grid/card-5.jpg",
      alt: "worker applying release agent on film-faced plywood formwork",
      day: "12",
      month: "Th.6",
      category: "KỸ THUẬT",
      categoryBg: "#2973b2",
      title: ["5 BÍ QUYẾT BẢO DƯỠNG", "VÁN ÉP PHỦ PHIM ĐỂ", "ĐẠT 10 LẦN TÁI SỬ", "DỤNG"],
      description: [
        "Cách vệ sinh, bôi dầu và bảo",
        "quản đúng cách có thể tăng",
        "gấp đôi số lần tái sử dụng ván",
        "coffa, tiết kiệm hàng chục",
        "triệu đồng chi phí vật liệu mỗi",
        "công trình.",
      ],
      views: "4,762",
    },
    {
      image: "/assets/news/grid/card-6.jpg",
      alt: "industrial factory team building event, Vietnamese workers",
      day: "01",
      month: "Th.6",
      category: "SỰ KIỆN",
      categoryBg: "#7a9c59",
      title: ["KỶ NIỆM 31 NĂM TU", "ANH 68 — HÀNH TRÌNH", "TỪ XƯỞNG NHỎ ĐẾN", "NHÀ MÁY 10.000M²"],
      description: [
        "Nhìn lại hành trình hơn 3 thập",
        "kỷ phát triển của Tu Anh 68,",
        "từ một xưởng sản xuất nhỏ",
        "trở thành nhà máy sản xuất",
        "ván ép phủ phim hàng đầu",
        "miền Bắc với 10.000m² mặt bằng.",
      ],
      views: "5,129",
    },
  ],
  loadMore: "XEM THÊM BÀI VIẾT",
} as const;

export const sidebarContent = {
  search: {
    heading: "TÌM KIẾM",
    placeholder: "Tìm bài viết...",
  },
  categories: {
    heading: "DANH MỤC",
    items: [
      { label: "Tất Cả Bài Viết", icon: "layers", count: "24", highlighted: true },
      { label: "Tin Thị Trường", icon: "trend", count: "9", highlighted: false },
      { label: "Kỹ Thuật & Hướng Dẫn", icon: "tech", count: "8", highlighted: false },
      { label: "Sự Kiện Công Ty", icon: "calendar", count: "7", highlighted: false },
    ],
  },
  trending: {
    heading: "TIN NỔI BẬT",
    items: [
      {
        image: "/assets/news/grid/thumb-1.jpg",
        alt: "plywood maintenance worker applying oil coating",
        category: "KỸ THUẬT",
        categoryBg: "#48a6a7",
        title: ["5 Bí Quyết Bảo Dưỡng Ván Ép Phủ Phim", "Đạt 10 Lần Tái Sử Dụng"],
        date: "12 Th.6, 2025",
      },
      {
        image: "/assets/news/grid/thumb-2.jpg",
        alt: "plywood factory anniversary celebration",
        category: "SỰ KIỆN",
        categoryBg: "#7a9c59",
        title: ["Kỷ Niệm 31 Năm Tu Anh 68 — Hành", "Trình Vươn Tầm"],
        date: "01 Th.6, 2025",
      },
      {
        image: "/assets/news/grid/thumb-3.jpg",
        alt: "Vietnam infrastructure construction project highway bridge",
        category: "THỊ TRƯỜNG",
        categoryBg: "#48a6a7",
        title: ["Nhu Cầu Ván Coffa Tăng 35% Theo Làn", "Sóng Đầu Tư Hạ Tầng"],
        date: "20 Th.6, 2025",
      },
      {
        image: "/assets/news/grid/thumb-4.jpg",
        alt: "Vietnam Build Expo exhibition hall",
        category: "SỰ KIỆN",
        categoryBg: "#7a9c59",
        title: ["Tu Anh 68 Tại Vietnam Build Expo", "2025"],
        date: "28 Th.6, 2025",
      },
    ],
  },
  contactCta: {
    heading: "CẦN BÁO GIÁ / VÁN PHỦ PHIM?",
    description: ["Liên hệ ngay để nhận bảng giá mới nhất và tư vấn chọn", "sản phẩm phù hợp công trình của bạn."],
    phone: "0983 570 760",
  },
} as const;
