export const projectsGridContent = {
  grid: [
    {
      id: "sc5",
      name: "SC5 Industrial Complex",
      nameUpper: "SC5 INDUSTRIAL COMPLEX",
      image: "/assets/projects/grid/project-01.jpg",
      status: "completed",
      category: "Công nghiệp",
      location: "Hà Nội",
      meta: "45,000 m²",
      materials: "Ván phủ phim 18mm – 12,000 tấm",
      large: true,
    },
    {
      id: "idj",
      name: "IDJ Tower",
      nameUpper: "IDJ TOWER",
      image: "/assets/projects/grid/project-02.jpg",
      status: "in-progress",
      category: "Dân dụng",
      location: "TP. HCM",
      meta: "32 tầng",
      materials: "Ván phủ phim 15mm",
      large: false,
    },
    {
      id: "licogi18",
      name: "Licogi 18 Residences",
      nameUpper: "LICOGI 18 RESIDENCES",
      image: "/assets/projects/grid/project-03.jpg",
      status: "completed",
      category: "Dân dụng",
      location: "Hà Nội",
      meta: "25 tầng",
      materials: "Ván phủ phim 18mm – 8,500 tấm",
      large: false,
    },
    {
      id: "hacc1-zone",
      name: "HACC1 Factory Zone",
      nameUpper: "HACC1 FACTORY ZONE",
      image: "/assets/projects/grid/project-04.jpg",
      status: "completed",
      category: "Công nghiệp",
      location: "Bình Dương",
      meta: "30,000 m²",
      materials: "Ván phủ phim 21mm – 9,200 tấm",
      large: false,
    },
    {
      id: "vinaconex",
      name: "Vinaconex Skyline",
      nameUpper: "VINACONEX SKYLINE",
      image: "/assets/projects/grid/project-05.jpg",
      status: "in-progress",
      category: "Dân dụng",
      location: "Hà Nội",
      meta: "40 tầng",
      materials: "Ván phủ phim 18mm – 15,000 tấm",
      large: false,
    },
    {
      id: "coma",
      name: "COMA Bridge Infrastructure",
      nameUpper: "COMA BRIDGE INFRASTRUCTURE",
      image: "/assets/projects/grid/project-06.jpg",
      status: "completed",
      category: "Hạ tầng giao thông",
      location: "Đà Nẵng",
      meta: "2.5 km",
      materials: "Ván phủ phim 18mm & 21mm",
      large: false,
    },
    {
      id: "ecoba",
      name: "ECOBA Industrial Park",
      nameUpper: "ECOBA INDUSTRIAL PARK",
      image: "/assets/projects/grid/project-07.jpg",
      status: "completed",
      category: "Công nghiệp",
      location: "Hưng Yên",
      meta: "80,000 m²",
      materials: "Ván phủ phim 18mm – 22,000 tấm | Ván phủ phim 21mm – 8,000 tấm",
      large: true,
    },
    {
      id: "sol-ec",
      name: "SOL E&C Overpass Project",
      nameUpper: "SOL E&C OVERPASS PROJECT",
      image: "/assets/projects/grid/project-08.jpg",
      status: "in-progress",
      category: "Hạ tầng giao thông",
      location: "Hải Phòng",
      meta: "1.8 km",
      materials: "Ván phủ phim 21mm – 11,000 tấm",
      large: false,
    },
    {
      id: "licogi-plant",
      name: "Licogi 18 Steel Plant",
      image: "/assets/projects/grid/project-09.jpg",
      status: "completed",
      category: "Công nghiệp",
      location: "Thái Nguyên",
      meta: "",
      materials: "Ván phủ phim 15mm & 18mm",
      large: false,
      nameUpper: "LICOGI 18 STEEL PLANT",
    },
    {
      id: "vnx-road",
      name: "Vinaconex Road Expansion",
      image: "/assets/projects/grid/project-10.jpg",
      status: "completed",
      category: "Hạ tầng giao thông",
      location: "Hà Nội",
      meta: "",
      materials: "Ván phủ phim 21mm – 7,000 tấm",
      large: false,
      nameUpper: "VINACONEX ROAD EXPANSION",
    },
    {
      id: "idj-commercial",
      name: "IDJ Commercial Center",
      image: "/assets/projects/grid/project-11.jpg",
      status: "in-progress",
      category: "Dân dụng",
      location: "Cần Thơ",
      meta: "",
      materials: "Ván phủ phim 15mm – 6,000 tấm",
      large: false,
      nameUpper: "IDJ COMMERCIAL CENTER",
    },
    {
      id: "hacc1-hospital",
      name: "HACC1 Medical Center",
      image: "/assets/projects/grid/project-12.jpg",
      status: "completed",
      category: "Dân dụng",
      location: "Hà Nội",
      meta: "",
      materials: "Ván phủ phim 18mm – 5,500 tấm",
      large: false,
      nameUpper: "HACC1 MEDICAL CENTER",
    },
  ],
} as const;
